// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrwkmzhoelglpwidehjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yd2ttemhvZWxnbHB3aWRlaGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzE3MDQsImV4cCI6MjA2NjcwNzcwNH0.kMYV7xgyQQmoCFnfqfOguGyYT1jmFYtMafdno1AE2Dc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});